__default__:
  account:       "eb-bb1271"
  partition:     "batch"
  ntasks:        1
  cpus-per-task: 16
  job-name:      "{rule}-%j"
  mail-type:     "ALL"
  mail-user:     "sr467@bath.ac.uk"
  output:        "{rule}-%j-%x.out"
  error:         "{rule}-%j-%x.err"
  time :         2

mask:
  time : 15

lammps:
  time : 30
  ntasks : 16
  cpus-per-task : 1

mergeReplicates:
  time : 15

sum_matrices:
  time : 60

mean_xyz:
  time : 360

create_gif:
  time : 60
