# Simulation output directory - will be created if neccessary.
workdir: /home/u/sr467/scratch/projects/MolecularDynamics/analysis
#workdir: /media/stephen/Data/modelling-ctcf
# LAMMPS config (rule: lammps)
timestep: 1000
reps: 200
threads: 12

#genome: /media/stephen/Data/genomes/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
genome: /home/u/sr467/scratch/projects/genomes/GRCh38/wgs/Homo_sapiens.GRCh38.dna.primary_assembly.fa

#ctcf: /home/stephen/phd/modelling/pipeline/config/ctcf_samples-local.csv
ctcf: /home/u/sr467/scratch/projects/MolecularDynamics/config/ctcf_samples.csv

region: GNG12_AS1
chr: 1
start: 65834316
end: 70234314
min_rep: 2

xlo: -500
xhi: 500
ylo: -500
yhi: 500
zlo: -500
zhi: 500
