# Simulation output directory - will be created if neccessary.
workdir: '/media/stephen/Data/modelling'

name: 'clustered_copolymer'

# Polymer generation config (rule: generate_polyer)
n_molecules: 1000
mode: 'clustered_copolymer'

# LAMMPS config (rule: lammps)
timestep: 500

# GIF creation confif (rule: create_gif)
delay: 10
loop: 0
