# Simulation output directory - will be created if neccessary.
workdir: '/home/u/sr467/scratch/projects/MolecularDynamics/analysis'

# LAMMPS config (rule: lammps)
timestep: 100
reps: 200
threads: 16
#window_size: 30
#overlap: 2
