# Simulation output directory - will be created if neccessary.
workdir: /home/u/sr467/scratch/projects/MolecularDynamics/analysis
tmpdir: /home/u/sr467/scratch/projects/MolecularDynamics/analysis
cluster: True

reps: 100
threads: 6
bases_per_bead: 250
genome: /home/u/sr467/scratch/projects/genomes/hg19/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz

ctcf :
    - /home/u/sr467/scratch/projects/genomes/hg19/tracks/GM12878-CTCF-hg19.bed
genes : /home/u/sr467/scratch/projects/genomes/hg19/tracks/UCSC-genes-hg19.bed
masking:
    /home/u/sr467/scratch/projects/genomes/hg19/tracks/GM12878-H3K4m1-hg19.bed : 1
    /home/u/sr467/scratch/projects/genomes/hg19/tracks/GM12878-H3K4m3-hg19.bed : 3

region: GNG12_AS1
chr: 1
start: 65834316
end: 70234314

HiC :
    matrix : /home/u/sr467/scratch/projects/genomes/hg19/tracks/GSE63525_GM12878_insitu_primary+replicate_combined_10000-chr1.cool
    log : True

dpi: 1200
xlo: -50
xhi: 50
ylo: -50
yhi: 50
zlo: -50
zhi: 50

# LAMMPS config (rule: lammps)
timestep: 500
warm_up: 20000
sim_time: 1000000
