# Simulation output directory - will be created if neccessary.
workdir: /media/stephen/Data/modelling-ctcf
tmpdir: /media/stephen/Data/modelling-ctcf
cluster: False

reps: 5
threads: 6
bases_per_bead: 1000
genome: /media/stephen/Data/genomes/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa

ctcf :
    - /media/stephen/Data/genomes/GRCh38/tracks/GM12878-CTCF-R1-hg38.bed
    - /media/stephen/Data/genomes/GRCh38/tracks/GM12878-CTCF-R2-hg38.bed
min_rep: 2
masking:
    - character: 1
      file: /media/stephen/Data/genomes/GRCh38/tracks/GM12878-H3K4m1-hg38.bed
    - character: 3
      file: /media/stephen/Data/genomes/GRCh38/tracks/GM12878-H3K4m3-hg38.bed

region: GNG12_AS1
chr: 1
start: 65834316
end: 70234314

dpi: 1200

xlo: -500
xhi: 500
ylo: -500
yhi: 500
zlo: -500
zhi: 500

# LAMMPS config (rule: lammps)
timestep: 500
warm_up: 10000
sim_time: 50000
